export const ColumnsNomal = [
    { value: 'description', label: 'Item Description' },
    { value: 'sku', label: 'SKU' },
    { value: 'venderReference', label: 'Vendor Item' },
    { value: 'actualCostUSD', label: 'Initial Cost (USD)' },
    { value: 'updatedCostUSD', label: 'Updated Cost (USD)' },
    { value: 'stoneDetail', label: 'Stone Detail' },
    { value: 'priceUSD', label: 'Retail Price (USD)' },
    { value: 'specialDiscount', label: 'Special Discount' },
    { value: 'specialDiscountPercent', label: 'Special Discount %' },
    { value: 'grossWeight', label: 'Item Weight (Grams)' },
    { value: 'size', label: 'Size' },
    { value: 'jewelsWeight', label: 'Jewelry Weight' },
    { value: 'site', label: 'Site' },
    { value: 'companyName', label: 'Company' },
    { value: 'warehouseName', label: 'Location' },
    { value: 'categoryName', label: 'Category Name' },
    { value: 'category', label: 'Category' },
    { value: 'article', label: 'Article' },
    { value: 'collectionName', label: 'Collection' },
    { value: 'setReference', label: 'Set Reference Number' },
    { value: 'lotNumber', label: 'Batch' },
    { value: 'netWeight', label: 'Gold weight (Grams)' },
    { value: 'stoneQty', label: 'Stone Qty' },
    { value: 'markup', label: 'Markup%' },
    { value: 'vendor', label: 'Vendor Code' },
    { value: 'vendorName', label: 'Vendor Name' },
    { value: 'metalColorName', label: 'Metal Colour' },
    { value: 'metalTypeName', label: 'Metal Type' },
    { value: 'dominantStoneName', label: 'Dominant Stone' },
    { value: 'brandName', label: 'Brand' },
    { value: 'complicationName', label: 'Complication' },
    { value: 'strapTypeName', label: 'Strap Type' },
    { value: 'strapColorName', label: 'Strap Color' },
    { value: 'buckleTypeName', label: 'Buckle Type' },
    { value: 'dialIndexName', label: 'Dial Index' },
    { value: 'dialColorName', label: 'Dial Color' },
    { value: 'movementName', label: 'Movement' },
    { value: 'serialNumber', label: 'Serial #' },
    { value: 'limitedEdition', label: 'Limited Edition' },
    { value: 'limitedEditionNumber', label: 'Limited Edition #' },
    { value: 'itemCreatedDate', label: 'Created Date' }
];
export const ColumnsViewAsSet = [
    { value: 'description', label: 'Description' },
    { value: 'sku', label: 'SKU' },
    { value: 'hierarchy', label: 'Category Name' },
    { value: 'company', label: 'Company' },
    { value: 'warehouse', label: 'Location' },
    { value: 'grossWeight', label: 'Item Weight (Grams)' },
    { value: 'stoneDetail', label: 'Stone Detail' }
];
