FROM alpine
MAINTAINER Korakod Chaisongkram (leointer@gmail.com)
LABEL Description="MOL Build Container" Version="2.0"
ENV NODE_VERSION=v6.2.2 NPM_VERSION=3.9.5
RUN apk update && \
    apk add nodejs
