FROM node:6
MAINTAINER Korakod Chaisongkram (korakod.chaisongkram@itorama.com)
LABEL Description="MOL Build Container" Version="1.0"
RUN apt-get update
RUN mkdir /web && \
    mkdir /web/code && \
    mkdir /web/logs
COPY ./ /web/code
WORKDIR /web/code
RUN npm i
RUN npm install pm2 -g
RUN npm install gulp-cli -g
RUN gulp
CMD ["npm","run","build",":","test"]
CMD ["pm2-runtime","start","process.json","--env","test"]
EXPOSE 3005
