CREATE TABLE mol.Authentication (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  user VARCHAR(255) DEFAULT NULL,
  device VARCHAR(255) DEFAULT NULL,
  token VARCHAR(255) DEFAULT NULL,
  ipad TINYINT(1) DEFAULT 0,
  PRIMARY KEY (id),
  INDEX user (user)
)
ENGINE = INNODB
AUTO_INCREMENT = 3857
AVG_ROW_LENGTH = 556
CHARACTER SET latin1
COLLATE latin1_swedish_ci;