CREATE TABLE mol.PermissionOnhandLocation (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  type VARCHAR(255) DEFAULT NULL,
  places LONGTEXT DEFAULT NULL,
  permission INT(11) DEFAULT NULL,
  createdAt DATETIME DEFAULT NULL,
  updatedAt DATETIME DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1349
AVG_ROW_LENGTH = 117
CHARACTER SET latin1
COLLATE latin1_swedish_ci;