CREATE TABLE mol.PermissionSalesWarehouse (
  id INT(11) NOT NULL AUTO_INCREMENT,
  type VARCHAR(255) DEFAULT NULL,
  places LONGTEXT DEFAULT NULL,
  permission INT(11) DEFAULT NULL,
  createdAt DATETIME DEFAULT NULL,
  updatedAt DATETIME DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 402
AVG_ROW_LENGTH = 3780
CHARACTER SET utf8
COLLATE utf8_general_ci;