CREATE TABLE mol.PermissionSalesChannel (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  type VARCHAR(255) DEFAULT NULL,
  places LONGTEXT DEFAULT NULL,
  permission INT(11) DEFAULT NULL,
  createdAt DATETIME DEFAULT NULL,
  updatedAt DATETIME DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 275
AVG_ROW_LENGTH = 2048
CHARACTER SET utf8
COLLATE utf8_general_ci;