CREATE TABLE mol.User (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  firstName VARCHAR(255) DEFAULT NULL,
  lastName VARCHAR(255) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  username VARCHAR(255) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  currency VARCHAR(3) DEFAULT NULL,
  role VARCHAR(255) DEFAULT NULL,
  status TINYINT(1) DEFAULT NULL,
  company VARCHAR(255) DEFAULT NULL,
  location VARCHAR(255) DEFAULT NULL,
  warehouse VARCHAR(255) DEFAULT NULL,
  permission INT(11) DEFAULT NULL,
  webOnly TINYINT(1) DEFAULT NULL,
  movement TINYINT(4) NOT NULL DEFAULT 0,
  createdAt DATETIME DEFAULT NULL,
  updatedAt DATETIME DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX email (email),
  UNIQUE INDEX username (username)
)
ENGINE = INNODB
AUTO_INCREMENT = 158
AVG_ROW_LENGTH = 555
CHARACTER SET latin1
COLLATE latin1_swedish_ci;