USE [MWD_DB]

SELECT [FROMCURRENCYCODE] AS 'from'
      ,[TOCURRENCYCODE] AS 'to'
      ,[EXCHANGERATE] AS 'exchangeRate'
	,[FROMDATE] AS 'fromDate'
	,DATEADD(MS, -3, DATEADD(D, DATEDIFF(D, 0, [TODATE]) + 1, 0)) AS 'toDate'
FROM [dbo].[ITO_EXCHANGERATE]
ORDER BY [FROMCURRENCYCODE], [TOCURRENCYCODE]
