USE [MWD_DB]

DECLARE @START DATETIME
DECLARE @END DATETIME
SELECT @START = DATEADD(D, DATEDIFF(D, 0, GETUTCDATE()), 0)
SELECT @END = DATEADD(MS, -3, DATEADD(D, DATEDIFF(D, 0, GETDATE()) + 1, 0))

SELECT [FROMCURRENCYCODE] AS 'from'
      ,[TOCURRENCYCODE] AS 'to'
      ,[EXCHANGERATE] AS 'exchangeRate'
FROM [dbo].[ITO_EXCHANGERATE]
WHERE [FROMDATE] <= @START AND [TODATE] >= @END
ORDER BY [FROMCURRENCYCODE], [TOCURRENCYCODE]
