USE [ITORAMA]

SELECT  [Id] AS 'id'
        ,[SetReference] AS 'setReference'
        ,UPPER([Reference]) AS 'reference'
        ,[ItemType] AS 'itemType'
        ,[Priority] AS 'priority'
        ,[Description] AS 'description'
        ,[Price] AS 'price'
        ,[ActualCost] AS 'actualCost'
        ,[UpdatedCost] AS 'updatedCost'
        ,[Markup] AS 'markup'
        ,[Warehouse] AS 'warehouse'
        ,[WarehouseName] AS 'warehouseName'
        ,[Currency] AS 'currency'
        ,[SKU] AS 'sku'
        ,[VendorReferance] AS 'venderReference'
        ,[SpecialDiscount] AS 'specialDiscount'
        ,[SpecialDiscPercent] AS 'specialDiscountPercent'
        ,[RomanceNote] AS 'setRomanceNote'
        ,[SetName] AS 'setName'
        ,[Company] AS 'company'
        ,[CompanyName] AS 'companyName'
        ,[SetImageName] AS 'setImageName'
        ,[SetImageType] AS 'setImageType'
        ,[DefaultSetImage] AS 'defaultSetImage'
        ,[LastModifiedDateSetImage] AS 'lastModifiedDateSetImage'
        ,[ImageName] AS 'imageName'
        ,[ImageType] AS 'imageType'
        ,[DefaultImage] AS 'defaultImage'
        ,[LastModifiedDateImage] AS 'lastModifiedDateImage'
        ,[Type] AS 'type'
        ,[Hierarchy] AS 'hierarchy'
        ,[GrossWeight] AS 'grossWeight'
        ,[StoneDetail] AS 'stoneDetail'
        ,[CreatedDate] AS 'createdDate'
FROM    [ITORAMA].[dbo].[SetItem]
ORDER BY    [SetReference], [Priority] DESC, [Reference]
