SELECT [Id] AS 'id'
      ,[Reference] AS 'reference'
      ,ISNULL([Description], '') AS 'description'
      ,[Sku] AS 'sku'
      ,[SalesId] AS 'salesId'
      ,[Quantity] AS 'quantity'
      ,ISNULL([SalesPersonId], '') AS 'salesPerson'
      ,ISNULL([SalesPersonName], '') AS 'salesPersonName'
      ,ISNULL([Warehouse], '') AS 'warehouse'
      ,ISNULL([WarehouseName], '') AS 'warehouseName'
      ,ISNULL([InvoicedId], '') AS 'invoicedId'
      ,[InvoiceDate] AS 'invoiceDate'
      ,[SumLineDiscReporting] AS 'sumLineDiscReporting'
      ,[NetAmount] AS 'netAmount'
      ,[GroupCost] AS 'groupCost'
      ,[UpdatedCost] AS 'updatedCost'
      ,[PublicPriceReporting] AS 'publicPriceReporting'
      ,[PP] AS 'publicPrice'
      ,[CValueReporting] AS 'cValueReporting'
      ,[Discount_amount_USD] AS 'discountAmountUSD'
      ,[Margin] AS 'margin'
      ,[DiscPercent] AS 'discPercent'
      ,ISNULL([Store], '') AS 'store'
      ,ISNULL([SalesChannelType], '') AS 'salesChannelType'
      ,ISNULL([CustomerId], '') AS 'customer'
      ,ISNULL([CustomerName], '') AS 'customerName'
      ,ISNULL([ArticleCode], '') AS 'article'
      ,ISNULL([ArticleDescription], '') AS 'articleName'
      ,ISNULL([CategoryCode], '') AS 'category'
      ,ISNULL([CategoryDescription], '') AS 'categoryName'
      ,ISNULL([CollectionCode], '') AS 'collection'
      ,ISNULL([CollectionDescription], '') AS 'collectionName'
      ,ISNULL([BrandCode], '') AS 'brand'
      ,ISNULL([BrandDescription], '') AS 'brandName'
      ,[MustHave] AS 'mustHave'
      ,ISNULL([InventSizeId], '') AS 'inventSizeId'
      ,ISNULL([InventSiteId], '') AS 'inventSiteId'
      ,[MarkupPercentage] AS 'markupPercentage'
      ,ISNULL([RetailProductCategory], '') AS 'retailProductCategory'
      ,ISNULL([Hierarchy], '') AS 'hierarchy'
      ,ISNULL([Site], '') AS 'site'
      ,[NetAmount_Local] AS 'netAmountLocal'
      ,[Tax_Local] AS 'taxLocal'
      ,ISNULL([CurrencyCode], '') AS 'currencyCode'
      ,ISNULL([DataAreaId], '') AS 'dataAreaId'
      ,ISNULL([Partition], '') AS 'partition'
      ,[PostedDate] AS 'postedDate'
      ,ISNULL([CatRecId], '') AS 'catRecId'
      ,ISNULL([Article_Grouping], '') AS 'articleGrouping'
      ,ISNULL([StoneDetail], '') AS 'stoneDetail'
      ,ISNULL([DominantStone], '') AS 'dominantStone'
	  ,ISNULL([CertificateNumber], '') AS 'certificateNumber'
  FROM [ITORAMA].[dbo].[SoldItems]
  WHERE [Id] BETWEEN @from AND @to
  ORDER BY [Id]
