FROM alpine
MAINTAINER Korakod Chaisongkram (leointer@gmail.com)
LABEL Description="Clear-Files Build Container" Version="1.0"
RUN apk update && \
    apk add nodejs
RUN mkdir /clear-files
RUN mkdir /clear-files/logs
COPY ./ /clear-files/
WORKDIR /clear-files
RUN npm i
RUN npm install pm2 -g
CMD ["pm2-runtime","start","process.json","--env","production"]
