SELECT [AccountNumber]
      ,[FirstName]
      ,[LastName]
      ,[MiddleName]
      ,[RetailMobilePrimary]
      ,[RetailMobileSecondary]
      ,[Email]
FROM  [ITORAMA].[dbo].[Customers]
GROUP BY [AccountNumber],[FirstName],[LastName],[MiddleName],[RetailMobilePrimary],[RetailMobileSecondary],[Email]
