SELECT [INVENTLOCATIONID] AS code
      ,[INVENTSITEID] AS locationid
      ,[NAME] AS name
      ,UPPER([DATAAREAID]) AS comid
FROM  [MWD_DB].[dbo].[CRWWAREHOUSE]
GROUP BY [INVENTLOCATIONID],[INVENTSITEID],[NAME],[DATAAREAID]
