const host = HOSTNAME || 'localhost';

export const ROOT_URL = `//${host}:3002`;
export const FETCH_OPTIONS = 'FETCH_OPTIONS';
export const SELECTED_COMPANY = 'SELECTED_COMPANY';
export const SELECTED_WAREHOUSES = 'SELECTED_WAREHOUSES';
export const GET_ONHANDWAREHOUSES = 'GET_ONHANDWAREHOUSES';
export const SET_HIERARCHY = 'SET_HIERARCHY';
export const SET_NOTUSEHIERARCHY = 'SET_NOTUSEHIERARCHY';
export const GET_SALESWAREHOUSES = 'GET_SALESWAREHOUSES';
export const SET_SALESHIERARCHY = 'SET_SALESHIERARCHY';
export const SET_NOTUSESALESHIERARCHY = 'SET_NOTUSESALESHIERARCHY';
