const host = HOSTNAME || 'localhost';

export const ROOT_URL = `//${host}:3002/`;
export const FETCH_PRODUCTDETAIL = 'FETCH_PRODUCTDETAIL';
export const FETCH_GEMATTRDETAIL = 'FETCH_GEMATTRDETAIL';
export const FETCH_PRODUCTRELETED = 'FETCH_PRODUCTRELETED';
export const FETCH_SETREFERENCE = 'FETCH_SETREFERENCE';
export const GET_CATALOGNAME = 'GET_CATALOGNAME';
export const ADD_CATALOG = 'ADD_CATALOG';
export const ADD_CATALOG_SUCCESS = 'Add to catalog success';
export const GET_CERTIFICATE = 'GET_CERTIFICATE';
export const GET_LOTNUMBER = 'GET_LOTNUMBER';
export const GET_LOTNUMBERPAGE = 'GET_LOTNUMBERPAGE';
export const GET_MOVEMENT = 'GET_MOVEMENT';
export const FETCH_SETDETAILS = 'FETCH_SETDETAILS';
