const host = HOSTNAME || 'localhost';

export const ROOT_URL = `//${host}:3002/`;
export const FETCH_PRODUCTDETAIL = 'FETCH_PRODUCTDETAIL';
export const FETCH_GEMATTRDETAIL = 'FETCH_GEMATTRDETAIL';
export const FETCH_PRODUCTRELETED = 'FETCH_PRODUCTRELETED';
export const FETCH_SETREFERENCE = 'FETCH_SETREFERENCE';
