const host = HOSTNAME || 'localhost';

export const ROOT_URL = `//${host}:${(ENVIRONMENT!='staging')?3002:4002}`;
export const FETCH_ALL_RELATED_ITEMS = 'FETCH_ALL_RELATED_ITEMS';
export const SET_RELATEDITEM = 'SET_RELATEDITEM';
export const ADD_RELATED_ITEMS = 'ADD_RELATED_ITEMS';
export const SET_RELATEDITEM_SOURCE = 'SET_RELATEDITEM_SOURCE';
export const SET_RELATEDITEM_ID = 'SET_RELATEDITEM_ID';
export const FETCH_RELATED_ITEM_ID = 'FETCH_RELATED_ITEM_ID';
export const EDIT_RELATED_ITEM = 'EDIT_RELATED_ITEM';
export const DELETE_RELATED_ITEM = 'DELETE_RELATED_ITEM';
export const SET_RELATEDITEM_SELECTED = 'SET_RELATEDITEM_SELECTED';
export const FETCH_EXPORT_RELATE_ITEMS = 'FETCH_EXPORT_RELATE_ITEMS';